import torch
import torch.nn as nn
from torchvision import transforms, models
from ultralytics import YOLO
from PIL import Image
import cv2
import numpy as np

# =====================================================================
# 1. INITIALIZATION & MODEL LOADING
# =====================================================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Loading pipeline on device: {device}...\n")

# Define the classes exactly as trained
class_names = ['Duplicate_Element', 'In_plane', 'Out_of_plane']

# --- Load the ResNet-18 Gatekeeper (Classifier) ---
resnet = models.resnet18(weights=None)
resnet.fc = nn.Linear(resnet.fc.in_features, 3)
resnet.load_state_dict(torch.load("resnet18_fea_anomaly.pth", map_location=device))
resnet = resnet.to(device)
resnet.eval()

# --- Load the YOLOv26 Localizer (Bounding Boxes) ---
# Ensure this path points to the 'best.pt' file generated by your YOLO training
yolo = YOLO("./yolo_workspace/runs/detect/train/weights/best.pt") 

# =====================================================================
# 2. THE GATEKEEPER INFERENCE PIPELINE
# =====================================================================
def analyze_fea_image(image_path):
    print(f"{'='*50}")
    print(f"ANALYZING: {image_path}")
    print(f"{'='*50}")
    
    # --- PHASE 1: CNN CLASSIFICATION ---
    try:
        img_pil = Image.open(image_path).convert('RGB')
    except Exception as e:
        print(f"Error loading image: {e}")
        return

    # Preprocess exactly as done during ResNet training
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    
    img_tensor = transform(img_pil).unsqueeze(0).to(device)
    
    with torch.no_grad():
        outputs = resnet(img_tensor)
        # Apply softmax to get confidence percentages
        probabilities = torch.nn.functional.softmax(outputs[0], dim=0)
        confidence, predicted = torch.max(probabilities, 0)
        
    predicted_class = class_names[predicted.item()]
    conf_score = confidence.item() * 100
    
    print(f"[Phase 1] ResNet-18 Classification : {predicted_class} ({conf_score:.1f}% confidence)")
    
    # --- PHASE 2: YOLO LOCALIZATION ---
    print(f"[Phase 2] Executing YOLO for spatial bounding boxes...")
    
    # Pass the raw image path directly to YOLO (it handles its own 640x640 preprocessing)
    results = yolo(image_path, verbose=False)
    
    # --- PHASE 3: VISUALIZATION ---
    for r in results:
        # r.plot() returns a numpy array (BGR format for OpenCV) with the boxes drawn
        im_array = r.plot()  
        
        # Add the CNN Gatekeeper prediction as a master title at the top of the image
        text = f"CNN Gatekeeper: {predicted_class} ({conf_score:.1f}%)"
        font = cv2.FONT_HERSHEY_SIMPLEX
        
        # Draw a black background rectangle for the text
        cv2.rectangle(im_array, (0, 0), (im_array.shape[1], 40), (0, 0, 0), -1)
        # Add the green text over the black bar
        cv2.putText(im_array, text, (15, 28), font, 0.8, (0, 255, 0), 2, cv2.LINE_AA)
        
        # Convert OpenCV BGR back to PIL RGB for easy display
        im_array_rgb = cv2.cvtColor(im_array, cv2.COLOR_BGR2RGB)
        img_with_boxes = Image.fromarray(im_array_rgb)
        
        # Display the image on screen
        img_with_boxes.show()
        
        # Optionally, save the result to disk
        # output_name = f"analyzed_{image_path.split('/')[-1]}"
        # img_with_boxes.save(output_name)
        # print(f"Saved result to {output_name}")

# =====================================================================
# 3. EXECUTION
# =====================================================================
if __name__ == '__main__':
    # Test the pipeline on a single image. 
    # Update this path to an actual image in your dataset.
    test_image = "./Image_dataset/Duplicate_Element/duplicate_elem_anomaly_02.png" 
    
    analyze_fea_image(test_image)